extends Node
# Declarative data that describe the static properties of our world.

# This oughta be read & generated by our CI system later
# along with build version/commit sha.
const VERSION = "0.1.3"
# Moon gravity
const GRAVITY: float = 1.62
# Scale of our models
const SCALE: float = .2

